spring.application.name=SpringAIOllama
spring.ai.ollama.base-url=http://localhost:11434

#Chat Model
spring.ai.ollama.chat.model=gemma4:12b
spring.ai.ollama.chat.think=false

#Embedding Model
spring.ai.model.embedding=ollama
spring.ai.ollama.embedding.model=nomic-embed-text

# Don't download models automatically
spring.ai.ollama.init.pull-model-strategy=never

# Vector Store Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.ai.vectorstore.redix.index-name=product-index
spring.ai.vectorstore.redix.prefix=product

spring.main.allow-bean-definition-overriding=true

spring.sql.init.schema-locations=classpath:init/schema.sql
spring.sql.init.mode=always
spring.ai.vectorstore.pgvector.dimensions=768

spring.data.redis.client-type=jedis

spring.ai.vectorstore.redis.initialize-schema=true
#docker run -d --name redis-stack -p 6379:6379 -p 8001:8001 redis/redis-stack:latest