spring.application.name=SpringAIOllama
spring.ai.ollama.base-url=http://localhost:11434

#Chat Model
spring.ai.ollama.chat.model=gemma4:12b
spring.ai.ollama.chat.think=false

#Embedding Model
spring.ai.model.embedding=ollama
spring.ai.ollama.embedding.model=nomic-embed-text

# Don't download models automatically
spring.ai.ollama.init.pull-model-strategy=never

# Vector Store Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/telusko
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver