spring.application.name=SpringEcom

#spring.datasource.url=jdbc:postgresql://localhost:5432/telusko
#spring.datasource.username=postgres
#spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.postgresql.Driver

# Set max file size for single file upload (e.g., 100MB)
spring.servlet.multipart.max-file-size=100MB
# Set max request size for total upload (e.g., multiple files in a single request)
spring.servlet.multipart.max-request-size=100MB

# Ollama Properties
spring.ai.ollama.base-url=http://localhost:11434

#Chat Model
spring.ai.ollama.chat.model=gemma4:12b
spring.ai.ollama.chat.think=false


# Don't download models automatically
spring.ai.ollama.init.pull-model-strategy=never

# Image Generation using Stability AI
spring.ai.stabilityai.api-key=Your-API-Key

# will be used by ImageModel, ImagePrompt, ImageResponse etc classes
spring.ai.model.image=stabilityai
spring.ai.stabilityai.image.model=stable-diffusion-xl-1024-v1-0
f
#Embedding Model
spring.ai.model.embedding=ollama
spring.ai.ollama.embedding.model=nomic-embed-text
# PG Vector Store
# Vector Store Configuration
spring.main.allow-bean-definition-overriding=true
spring.ai.vectorstore.pgvector.dimensions=1536

spring.sql.init.schema-locations=classpath:init/schema.sql
spring.sql.init.mode=always
